apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    tier: front-end
spec:
  containers:
    - name: nginx-container
      image: stacksimplify/kubenginx:1.0.0
      ports:
        - containerPort: 80

    