apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::225908212644:role/eksctl-eksdemo1-addon-iamserviceaccount-defau-Role1-aUQGXiesdVaj